
package pao.gui;

import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import pao.entities.SchoolClass;
import pao.entities.Student;
import pao.table_data.TableSchoolClass;


public class JFrameManagerStudent extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSudentManager
     */

    private Student editItem;
     private boolean  isEdit=false;

    public Student getEditItem() {
        return editItem;
    }
    
     public boolean getIsEdit() {
        return isEdit;
    }
    
    public JFrameManagerStudent(Student s) {
        initComponents();
        this.setResizable(false);
        
        editItem=s;
        
         comboBoxScoolClass.setModel(new ComboBoxModel<SchoolClass>() {
            
            Object curentSelect;
            
       
              TableSchoolClass tabel= TableSchoolClass.getInstance();
            
           @Override
            public void setSelectedItem(Object anItem) {
               curentSelect=anItem;
            }

            @Override
            public Object getSelectedItem() {
              return curentSelect;
            }

            @Override
            public int getSize() {
               return  tabel.size();
            }

            @Override
            public SchoolClass getElementAt(int index) {
               return  tabel.get(index);
            }

            @Override
            public void addListDataListener(ListDataListener l) {
               
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                 
            }
   });
        
        
        
        setControlStudent();
        
    }
    
    
      
    private void setControlStudent(){
        if(editItem==null){
            editItem= new Student();
        }
        
       txtStudentName.setText(editItem.getName());

       txtStudentLastName.setText(editItem.getLastName());
        
       txtStudentCity.setText(editItem.getCity());
        comboBoxScoolClass.setSelectedItem(editItem.getSchoolClass());

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentName = new javax.swing.JTextField();
        txtStudentLastName = new javax.swing.JTextField();
        txtStudentCity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStudentSave = new javax.swing.JButton();
        btnStudentCancel = new javax.swing.JButton();
        comboBoxScoolClass = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtStudentLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentLastNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Prenume");

        jLabel2.setText("Nume");

        jLabel4.setText("Oras");

        btnStudentSave.setText("Save");
        btnStudentSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentSaveActionPerformed(evt);
            }
        });

        btnStudentCancel.setText("Cancel");
        btnStudentCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("Clasa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(btnStudentSave)
                                .addGap(59, 59, 59)
                                .addComponent(btnStudentCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(txtStudentLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                                    .addComponent(txtStudentName))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(comboBoxScoolClass, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxScoolClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentSave)
                    .addComponent(btnStudentCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentLastNameActionPerformed

    private void btnStudentSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentSaveActionPerformed
      try{
          
          
          if(txtStudentName.getText().trim().length()==0){
              throw  new Exception("Adaugati numele complet");
          }
         
          
          if(txtStudentLastName.getText().trim().length()==0){
              throw  new Exception("Adaugati prenumele complet");
          }

          
          if(txtStudentCity.getText().trim().length()==0){
              throw  new Exception("Adaugati orasul complet");
          }
          
          
          if(comboBoxScoolClass.getSelectedIndex()==-1){
              throw  new Exception("Selectati o clasa");
          }
             
           editItem.setName(txtStudentName.getText().trim());
           editItem.setLastName(txtStudentLastName.getText().trim());
           editItem.setCity(txtStudentCity.getText().trim());
           
             editItem.setScoolClass((SchoolClass)comboBoxScoolClass.getSelectedItem());
          
           
           this.isEdit=true;
          this.dispose();
          
      }catch(Exception e){
             JOptionPane.showMessageDialog(this,  e.getMessage());
      }
        
    }//GEN-LAST:event_btnStudentSaveActionPerformed

    private void btnStudentCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCancelActionPerformed
        this.isEdit=false;
          this.dispose();
    }//GEN-LAST:event_btnStudentCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudentCancel;
    private javax.swing.JButton btnStudentSave;
    private javax.swing.JComboBox<pao.entities.SchoolClass> comboBoxScoolClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtStudentCity;
    private javax.swing.JTextField txtStudentLastName;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
