
package pao.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.AbstractListModel;
import javax.swing.JFrame;
import pao.entities.SchoolClass;
import pao.table_data.TableSchoolClass;

public class JFrameMain extends javax.swing.JFrame {

    
    private javax.swing.JFrame  thisParinte=this;
    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        repaint();
    }

        @Override
    public void repaint() {
         
           listScoolClass.setModel(new AbstractListModel<SchoolClass>() {
           
           TableSchoolClass tableSchoolClass= TableSchoolClass.getInstance();
           
           
            @Override
            public int getSize() {
              return tableSchoolClass.size();
            }

            @Override
            public SchoolClass getElementAt(int index) {
               return tableSchoolClass.get(index);
            }
       });
           
        
           super.repaint(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        listScoolClass = new javax.swing.JList<>();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listScoolClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listScoolClassMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listScoolClass);

        btnEdit.setText("Edit Data");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(624, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(btnEdit)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     
         thisParinte.setVisible(false);
      
        
         JFrmaeManagerLists jFrameManagerClassScool= new JFrmaeManagerLists();
         
        jFrameManagerClassScool.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
       
        jFrameManagerClassScool.setAlwaysOnTop(true);
        jFrameManagerClassScool.show();

        jFrameManagerClassScool.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                 thisParinte.setVisible(true);
                 thisParinte.repaint();
               
               
            }

        });
    }//GEN-LAST:event_btnEditActionPerformed

    private void listScoolClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listScoolClassMouseClicked
     
        if(evt.getClickCount()==2){
            if(listScoolClass.getSelectedIndex()!=-1){
                JFormCatalog fra= new JFormCatalog(listScoolClass.getSelectedValue());
                
                  fra.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE );
       
        fra.setAlwaysOnTop(true);
        fra.show();

        fra.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
               thisParinte.setVisible(true);
                 thisParinte.repaint();
               
               
            }

        });
                
                
            }
        }
    }//GEN-LAST:event_listScoolClassMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<SchoolClass> listScoolClass;
    // End of variables declaration//GEN-END:variables
}
